apiVersion: v1
kind: ConfigMap
metadata:
  name: downloader-script
data:
  download.sh: |
    #!/bin/bash
    apt-get update && apt-get install -y wget
    wget -E -k -p -nH --cut-dirs=1 https://www.csd.uoc.gr -P /data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: site-storage-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: csd-web-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csd-site
  template:
    metadata:
      labels:
        app: csd-site
    spec:
      initContainers: 
      - name: initial-download
        image: ubuntu:24.04
        command: ["/bin/bash", "/scripts/download.sh"]
        volumeMounts:
        - name: script-storage
          mountPath: /scripts
        - name: site-storage
          mountPath: /data
      containers: 
      - name: nginx-container
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: site-storage
          mountPath: /usr/share/nginx/html
      volumes:
      - name: script-storage
        configMap:
          name: downloader-script
      - name: site-storage
        persistentVolumeClaim:
          claimName: site-storage-pvc
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: csd-refresh-cron
spec:
  schedule: "15 2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: updater
            image: ubuntu:24.04
            command: ["/bin/bash", "/scripts/download.sh"]
            volumeMounts:
            - name: script-storage
              mountPath: /scripts
            - name: site-storage
              mountPath: /data
          restartPolicy: OnFailure
          volumes:
          - name: script-storage
            configMap:
              name: downloader-script
          - name: site-storage
            persistentVolumeClaim:
              claimName: site-storage-pvc